import React from 'react';
import {AbsoluteFill, Sequence, useVideoConfig} from 'remotion';
import {Beat, DEFAULT_THEME} from './theme';
import {HookTitle} from './templates/HookTitle';
import {ImageCard} from './templates/ImageCard';
import {InlineChart} from './templates/InlineChart';
import {QuotePull} from './templates/QuotePull';
import {RatioDots} from './templates/RatioDots';
import {StaticTakeover} from './templates/StaticTakeover';
import {StatPunch} from './templates/StatPunch';
import {VerticalTimeline} from './templates/VerticalTimeline';
import {WordPop} from './templates/WordPop';

// StyleShowcase — the golden comp. One 90-frame (3s) Sequence per template
// kind against a mid-gray background (#444) so legibility shadows are visible.
// Extend with every new template kind — this comp is the visual contract for
// the whole library. appear_sec / mark_at values are ABSOLUTE seconds
// consistent with each sequence's start, so the frame-exact convention
// (invariant 2) shows the right state at each sequence's midpoint frame.
//
// image kinds expect public/showcase-asset.png — generated by the e2e/golden
// verification, not committed.

const HOOK: Beat = {
  kind: 'hook_title',
  start_sec: 0,
  end_sec: 3,
  kicker: 'TWO PEOPLE · WITH AI',
  title: '$400M',
  vertical: 0.6,
};

const WORD_POP: Beat = {
  kind: 'word_pop',
  start_sec: 3,
  end_sec: 6,
  items: [
    {text: 'ChatGPT', appear_sec: 3.0},
    {text: '{Claude}', appear_sec: 4.0},
    {text: 'Grok', appear_sec: 5.0, accent: true},
  ],
};

const STAT: Beat = {
  kind: 'stat_punch',
  start_sec: 6,
  end_sec: 9,
  value: '10×',
  caption: 'faster than hand-editing',
};

const QUOTE: Beat = {
  kind: 'quote_pull',
  start_sec: 9,
  end_sec: 12,
  quote_text: 'The plan was never the bottleneck.\nThe setup was.',
  attribution: 'the M1 retro',
  chars_per_second: 16, // mid-sequence (1.5s in): ~19 chars typed, caret on line 1
};

const STATIC: Beat = {
  kind: 'static',
  start_sec: 12,
  end_sec: 15,
  image_path: 'showcase-asset.png',
  caption: 'REAL SCREENSHOT',
};

const IMAGE_CARD: Beat = {
  kind: 'image_card',
  start_sec: 15,
  end_sec: 18,
  image_path: 'showcase-asset.png',
  caption: 'REAL DASHBOARD',
};

const TIMELINE: Beat = {
  kind: 'vertical_timeline',
  start_sec: 18,
  end_sec: 21,
  title: 'THE PIPELINE',
  steps: [
    {heading: 'TRANSCRIBE', appear_sec: 18.4, description: 'word timestamps from Whisper'},
    {heading: 'ALIGN', appear_sec: 19.1},
    {heading: 'RENDER', appear_sec: 19.8, description: 'Remotion over the source'},
    {heading: 'VERIFY', appear_sec: 20.5},
  ], // mid-sequence (19.5s): two steps revealed, rail en route to step 3
};

const RATIO: Beat = {
  kind: 'ratio_dots',
  start_sec: 21,
  end_sec: 24,
  total: 12,
  marked: 9,
  polarity: 'negative',
  mark_at: 22.0, // flip settles by 22.4s, so the mid-sequence frame shows post-flip
  caption: '9 OF 12 CHURNED',
};

const CHART: Beat = {
  kind: 'inline_chart',
  start_sec: 24,
  end_sec: 27,
  title: 'TOKENS RE-READ PER MESSAGE',
  data: [12, 18, 26, 41, 63, 95],
  labels: ['msg 1', '', '', '', '', 'msg 20'],
  draw_duration: 1.2, // fully drawn by mid-sequence
};

export const StyleShowcase: React.FC = () => {
  const {fps} = useVideoConfig();
  // Same Sequence boundary rounding as EditedVideo.tsx — items inside beats
  // resolve their offsets against these exact frame numbers (invariant 2).
  const seg = (beat: Beat) => ({
    from: Math.round(beat.start_sec * fps),
    durationInFrames: Math.max(
      1,
      Math.round(beat.end_sec * fps) - Math.round(beat.start_sec * fps),
    ),
  });
  return (
    <AbsoluteFill style={{backgroundColor: '#444'}}>
      <Sequence {...seg(HOOK)}>
        <HookTitle beat={HOOK} theme={DEFAULT_THEME} />
      </Sequence>
      <Sequence {...seg(WORD_POP)}>
        <WordPop beat={WORD_POP} theme={DEFAULT_THEME} />
      </Sequence>
      <Sequence {...seg(STAT)}>
        <StatPunch beat={STAT} theme={DEFAULT_THEME} />
      </Sequence>
      <Sequence {...seg(QUOTE)}>
        <QuotePull beat={QUOTE} theme={DEFAULT_THEME} />
      </Sequence>
      <Sequence {...seg(STATIC)}>
        <StaticTakeover beat={STATIC} theme={DEFAULT_THEME} />
      </Sequence>
      <Sequence {...seg(IMAGE_CARD)}>
        <ImageCard beat={IMAGE_CARD} theme={DEFAULT_THEME} />
      </Sequence>
      <Sequence {...seg(TIMELINE)}>
        <VerticalTimeline beat={TIMELINE} theme={DEFAULT_THEME} />
      </Sequence>
      <Sequence {...seg(RATIO)}>
        <RatioDots beat={RATIO} theme={DEFAULT_THEME} />
      </Sequence>
      <Sequence {...seg(CHART)}>
        <InlineChart beat={CHART} theme={DEFAULT_THEME} />
      </Sequence>
    </AbsoluteFill>
  );
};
