#!/usr/bin/env python3
"""Slotify every decompiled layout in a brand pack: literal text labels →
`{{ text_N | default("literal") }}` slots, so the pack works as a fillable
template while the bare showcase render stays identical (defaults).

Also reports slot coverage per layout: literal text lines that could NOT be
slotified (braces in label) and picture lines without an image slot.

After slotifying, every layout gets auto-generated layout-picker frontmatter
(role / ideal_count / data_band / comparison + slot roles + image queries —
see feinschliff_builder.decompile.layout_profile_gen) and the brand gets a
`deck-map.yaml` mapping deck roles (cover/agenda/section/quote/closer/content)
to layouts. Without the frontmatter, `build_profile_table(strict=False)`
silently drops decompiled layouts and the /deck picker can never choose them.
Skip with `--no-profiles`.

Usage:
  uv run python scripts/slotify_layouts.py --brand-pack <…/brands/<brand>> [--dry-run] [--no-profiles]
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from feinschliff_builder.decompile.layout_profile_gen import (
    apply_profile,
    classify_layout,
    derive_deck_map,
)
from feinschliff_builder.decompile.cleanup import native_pic_rects, strip_native_text_doubles
from feinschliff_builder.decompile.slotify import (
    add_autoshrink,
    autoshrink_enabled,
    clip_text_to_images,
    clip_to_images_enabled,
    slotify_dsl,
    slotify_native_text,
)
from feinschliff_builder.verify.verify_map import load_verify_map

_DECK_MAP_HEADER = (
    "# Auto-generated by slotify_layouts.py — layout roles for deck planning.\n"
)


def _slide_indices(brand_pack: Path, names: list[str]) -> tuple[dict[str, int], int]:
    """Layout name → 1-based slide index. Prefers the brand's verify-map.yaml
    (`layouts:` mapping, the decompile source-slide order); falls back to the
    sorted-filename enumeration for unmapped names / mapless brands."""
    verify_map: dict[str, int] = {}
    try:
        verify_map = dict(load_verify_map(brand_pack).layouts)
    except FileNotFoundError:
        pass  # brand has no verify-map.yaml; fall back to filename enumeration
    except ValueError:
        pass  # malformed map; fall back gracefully
    indices = {
        name: verify_map.get(name, pos + 1) for pos, name in enumerate(names)
    }
    total = max(indices.values(), default=0)
    return indices, total


def _pack_width_emu(brand_pack: Path) -> float:
    """slide.width_emu from tokens.json (0.0 when absent — geometry check
    in strip_native_text_doubles then falls back to literal-only match)."""
    import json
    try:
        raw = json.loads((brand_pack / "tokens.json").read_text(encoding="utf-8"))
        return float(raw["slide"]["width_emu"]["$value"])
    except Exception:
        return 0.0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--brand-pack", required=True, type=Path)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--no-profiles", action="store_true",
                    help="skip frontmatter profile + deck-map generation")
    args = ap.parse_args()

    brand_pack = args.brand_pack.resolve()
    layouts_dir = brand_pack / "layouts"
    if not layouts_dir.is_dir():
        sys.exit(f"no layouts/ in {args.brand_pack}")

    clip_enabled = clip_to_images_enabled(brand_pack)
    total_slots = 0
    unslotified_text = 0
    unslotified_pics = 0
    slotified: dict[str, str] = {}  # layout name → slotified DSL text
    clip_log: dict[str, list[str]] = {}  # layout name → clip log lines
    for path in sorted(layouts_dir.glob("*.slide.dsl")):
        text = path.read_text(encoding="utf-8")
        new_text, slots = slotify_dsl(text)
        if not args.dry_run:
            # Native runs that double a regular text line's label render
            # stacked once a deck binds either copy — blank the native run
            # (the text slot is the single binding point), THEN slotify the
            # remaining native payload text. Sidecar payloads rewrite on
            # disk, so both passes are skipped on dry runs.
            new_text, doubles = strip_native_text_doubles(
                new_text, brand_pack / "assets",
                width_emu=_pack_width_emu(brand_pack))
            if doubles:
                print(f"  {path.name}: blanked {doubles} native text double(s)")
            new_text, native_slots, native_logs = slotify_native_text(
                new_text, brand_pack / "assets")
            for line in native_logs:
                print(f"  {path.name}: {line}")
            slots = slots + [ns["name"] for ns in native_slots]
        if clip_enabled:
            new_text, clips = clip_text_to_images(
                new_text,
                extra_images=native_pic_rects(
                    new_text, brand_pack / "assets",
                    width_emu=_pack_width_emu(brand_pack)))
            if clips:
                clip_log[path.name[: -len(".slide.dsl")]] = clips
        leftovers = [ln for ln in new_text.splitlines()
                     if ln.startswith("text ") and '"' in ln and "{{" not in ln]
        bare_pics = [ln for ln in new_text.splitlines()
                     if ln.startswith("picture ") and "{{" not in ln]
        unslotified_text += len(leftovers)
        unslotified_pics += len(bare_pics)
        total_slots += len(slots)
        flag = ""
        if leftovers:
            flag += f"  [{len(leftovers)} text left literal]"
        if bare_pics:
            flag += f"  [{len(bare_pics)} picture without slot]"
        print(f"  {path.name}: {len(slots)} text slots{flag}")
        if not args.dry_run and new_text != text:
            path.write_text(new_text, encoding="utf-8")
        slotified[path.name[: -len(".slide.dsl")]] = new_text

    mode = "(dry-run) " if args.dry_run else ""
    print(f"\n{mode}{total_slots} text slots across "
          f"{len(list(layouts_dir.glob('*.slide.dsl')))} layouts; "
          f"{unslotified_text} text lines left literal, "
          f"{unslotified_pics} pictures without slot")
    if clip_log:
        total_clips = sum(len(v) for v in clip_log.values())
        print(f"text-over-image clips: {total_clips} across {len(clip_log)} layout(s):")
        for name in sorted(clip_log):
            for msg in clip_log[name]:
                print(f"  {name}: {msg}")

    if not args.no_profiles and slotified:
        names = sorted(slotified)
        indices, total = _slide_indices(brand_pack, names)
        profiles: dict[str, dict] = {}
        for name in names:
            profile = classify_layout(
                slotified[name],
                layout_name=name,
                slide_index=indices[name],
                total_slides=total,
                asset_root=brand_pack / "assets",
                brand_dir=brand_pack,
            )
            profiles[name] = profile
            roles = {n: meta.get("role", "")
                     for n, meta in (profile.get("slots") or {}).items()}
            if autoshrink_enabled(brand_pack):
                slotified[name] = add_autoshrink(slotified[name], roles)
            if not args.dry_run:
                path = layouts_dir / f"{name}.slide.dsl"
                path.write_text(apply_profile(slotified[name], profile),
                                encoding="utf-8")
        flagged = {n: p["slot_warnings"] for n, p in profiles.items()
                   if p.get("slot_warnings")}
        if flagged:
            total_warnings = sum(
                len(msgs) for w in flagged.values() for msgs in w.values()
            )
            print(f"slot-warnings: {total_warnings} across {len(flagged)} layout(s):")
            for name in sorted(flagged):
                for slot, msgs in sorted(flagged[name].items()):
                    for msg in msgs:
                        print(f"  {name}.{slot}: {msg}")
        deck_map = derive_deck_map(profiles)
        if not args.dry_run:
            (brand_pack / "deck-map.yaml").write_text(
                _DECK_MAP_HEADER + yaml.safe_dump(
                    deck_map, sort_keys=False, allow_unicode=True,
                    default_flow_style=None),
                encoding="utf-8")
        role_counts: dict[str, int] = {}
        for profile in profiles.values():
            role_counts[profile["role"]] = role_counts.get(profile["role"], 0) + 1
        roles = ", ".join(f"{r} {n}" for r, n in sorted(
            role_counts.items(), key=lambda kv: (-kv[1], kv[0])))
        print(f"{mode}profiles: {len(profiles)} layouts, roles: {roles}, "
              f"deck-map {'skipped' if args.dry_run else 'written'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
