#!/usr/bin/env python3
"""Generate every plugin's bin/<name> launcher and build-wheels.sh from one
manifest + two templates — the single source of truth for the feinschmiede
family's bootstrap layer.

The launchers/build-wheels scripts used to be hand-mirrored across five plugins
(G7 in the suite review): a fix to the venv-bootstrap or wheelhouse logic had to
be copied five times and drifted in between. They now derive from PLUGINS +
LAUNCHER_TMPL + BUILD_WHEELS_TMPL below, so a bootstrap change is one edit here.

Usage:
    python3 scripts/gen_launchers.py            # (re)write all generated files
    python3 scripts/gen_launchers.py --check    # CI: fail if any file is stale

The generated files are committed (they must be on PATH/executable at install
time, before this generator could ever run). CI runs --check to keep them in
sync with this manifest.
"""
from __future__ import annotations

import argparse
import stat
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# name -> bootstrap spec.
#   builds:      workspace dirs to `uv build` (first entry is the plugin itself;
#                wheel basenames use underscores, dirs use hyphens).
#   third_party: pip-download closure (charset-normalizer's universal fallback
#                is appended by the template for every plugin).
#   env_tail:    extra `export`s appended after the bootstrap, before exec.
PLUGINS: dict[str, dict] = {
    "feinschliff": {
        "builds": ["feinschliff", "feinschmiede"],
        "third_party": ["python-pptx", "lxml", "pillow", "cairosvg",
                        "pyphen", "jsonschema", "pyyaml", "rough"],
        "env_tail": "office",
    },
    "feinbild": {
        "builds": ["feinbild", "feinschmiede"],
        "third_party": ["requests", "cairosvg", "rough", "jsonschema", "pyyaml"],
        "env_tail": "none",
    },
    "feinklang": {
        "builds": ["feinklang"],
        "third_party": ["requests"],
        "env_tail": "none",
    },
    "feinschnitt": {
        "builds": ["feinschnitt"],
        "third_party": ["google-generativeai"],
        "env_tail": "recorder",
    },
    "feinschliff-builder": {
        "builds": ["feinschliff-builder", "feinschliff", "feinschmiede"],
        "third_party": ["python-pptx", "lxml", "pillow", "cairosvg", "pyphen",
                        "jsonschema", "pyyaml", "rough", "anthropic"],
        "env_tail": "none",
    },
    "feinblick": {
        # stdlib-only: the wheelhouse is just our own wheel, no third-party deps.
        "builds": ["feinblick"],
        "third_party": [],
        "env_tail": "none",
    },
}

ENV_TAILS = {
    "none": "",
    "office": (
        "\n"
        "# Make this plugin's bundled toolkit layouts + brand packs discoverable by\n"
        "# the engine/office discovery (additive — a user's own paths still win).\n"
        'export FEINSCHLIFF_LAYOUT_PATH="${FEINSCHLIFF_LAYOUT_PATH:+$FEINSCHLIFF_LAYOUT_PATH:}$PLUGIN_ROOT/layouts"\n'
        'export FEINSCHLIFF_BRAND_PATH="${FEINSCHLIFF_BRAND_PATH:+$FEINSCHLIFF_BRAND_PATH:}$PLUGIN_ROOT/brands"\n'
    ),
    "recorder": (
        "\n"
        "# Let `feinschnitt record` find the bundled recipe profiles/schema (the\n"
        "# recorder logic lives in the wheel, not under skills/, so it can't\n"
        "# self-locate them).\n"
        'export FEINSCHNITT_RECORDER_HOME="$PLUGIN_ROOT/skills/cli-recorder"\n'
    ),
}

LAUNCHER_TMPL = r'''#!/usr/bin/env bash
# @NAME@ launcher — the reusable "a plugin exposes a CLI" pattern for the
# feinschmiede family. GENERATED by scripts/gen_launchers.py — do not edit by
# hand; edit the template there and re-run it.
#
# First run provisions a self-contained venv from the plugin's bundled wheels
# (offline), then execs the real CLI; later runs just exec the installed CLI.
# This file lives in bin/, so it is on PATH whenever the plugin is enabled —
# sibling plugins/skills call `@NAME@ …` as a bare command, never reaching into
# our files. The venv is keyed on a content signature of the wheelhouse PLUS the
# plugin's pyproject.toml, so a plugin update (new wheels or bumped source)
# rebuilds the persistent venv instead of running stale code; a best-effort
# flock serializes concurrent first runs; the venv is built in place (venvs are
# not relocatable) and rm -rf'd on a partial bootstrap so every retry self-heals.
set -euo pipefail

PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-"$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"}"
DATA_DIR="${CLAUDE_PLUGIN_DATA:-"${XDG_DATA_HOME:-$HOME/.local/share}/feinschmiede/@NAME@"}"

VENV="$DATA_DIR/venv"
WHEELS="$PLUGIN_ROOT/wheels"
CLI="$VENV/bin/@NAME@"
READY="$VENV/.@NAME@-ready"

_BOOTSTRAPPING=0
_cleanup() { if [[ "$_BOOTSTRAPPING" -eq 1 && ! -f "$READY" ]]; then rm -rf "$VENV"; fi; }
trap _cleanup EXIT

_have_wheels() {
  [[ -d "$WHEELS" ]] || return 1
  local w
  for w in "$WHEELS"/*.whl; do [[ -e "$w" ]] && return 0; done
  return 1
}

_wheelhouse_sig() {
  # Sorted wheel filenames + byte sizes. Empty-glob-safe: returns a fixed token
  # when no wheels are present (so `set -e`/pipefail can't kill the launcher on
  # an unmatched glob), which simply forces a (re)build.
  _have_wheels || { printf 'no-wheels'; return 0; }
  { for w in "$WHEELS"/*.whl; do printf '%s %s\n' "${w##*/}" "$(wc -c <"$w")"; done | sort; } \
    | cksum | awk '{print $1}'
}

_source_sig() {
  # Hash the declared version/deps so an in-place source update that leaves a
  # stale wheelhouse still rebuilds the venv (the "automatic" content-hash).
  [[ -f "$PLUGIN_ROOT/pyproject.toml" ]] || { printf 'no-src'; return 0; }
  cksum < "$PLUGIN_ROOT/pyproject.toml" | awk '{print $1}'
}

_build_wheels_from_source() {
  # A marketplace/git install ships no wheels (they are gitignored). On first run
  # build them from the bundled source — needs uv + network for the dep closure.
  # PyPI Trusted Publishing (Phase 3) will replace this with a plain index install.
  [[ -f "$PLUGIN_ROOT/build-wheels.sh" ]] || return 1
  command -v uv >/dev/null 2>&1 || return 1
  echo "@NAME@: no prebuilt wheels — building from bundled source (first run; needs network)…" >&2
  bash "$PLUGIN_ROOT/build-wheels.sh" >&2
}

_bootstrap() {
  local sig="$1"
  if ! _have_wheels; then
    echo "@NAME@: no bundled wheels at $WHEELS and could not build them." >&2
    echo "@NAME@: needs 'uv' + network (or run build-wheels.sh in the plugin dir)." >&2
    exit 1
  fi

  mkdir -p "$DATA_DIR"
  exec 9>"$DATA_DIR/.bootstrap.lock" || true
  if command -v flock >/dev/null 2>&1; then flock 9 || true; fi
  if [[ -f "$READY" && "$(cat "$READY" 2>/dev/null)" == "$sig" ]]; then
    exec 9>&-
    return 0
  fi

  echo "@NAME@: first run — provisioning venv at $VENV (offline, from bundled wheels)…" >&2
  _BOOTSTRAPPING=1
  rm -rf "$VENV"

  local pyver=""
  [[ -f "$WHEELS/.python-version" ]] && pyver="$(cat "$WHEELS/.python-version")"

  if command -v uv >/dev/null 2>&1; then
    uv venv ${pyver:+--python "$pyver"} "$VENV" >&2
    uv pip install --reinstall --python "$VENV/bin/python" --no-index --find-links "$WHEELS" @NAME@ >&2
  else
    local py=""
    [[ -n "$pyver" ]] && py="$(command -v "python$pyver" || true)"
    [[ -z "$py" ]] && py="$(command -v python3 || true)"
    if [[ -z "$py" ]]; then
      echo "@NAME@: need 'uv' or 'python3' (with venv support); neither was found." >&2
      exit 1
    fi
    "$py" -m venv "$VENV" >&2
    if ! "$VENV/bin/python" -m pip --version >/dev/null 2>&1; then
      "$VENV/bin/python" -m ensurepip --upgrade >&2 || {
        echo "@NAME@: the venv has no pip and ensurepip failed — install 'uv' or python3-venv." >&2
        exit 1
      }
    fi
    "$VENV/bin/python" -m pip install --force-reinstall --no-index --find-links "$WHEELS" @NAME@ >&2
  fi

  printf '%s\n' "$sig" > "$READY"
  _BOOTSTRAPPING=0
  exec 9>&-
}

# Build the wheelhouse from bundled source whenever none is present (fresh
# marketplace/git install, or an update that dropped the gitignored wheels).
if ! _have_wheels; then
  _build_wheels_from_source || true
fi

SIG="$(_wheelhouse_sig).$(_source_sig)"
if [[ ! -f "$READY" || "$(cat "$READY" 2>/dev/null)" != "$SIG" ]]; then
  _bootstrap "$SIG"
fi
@ENV_TAIL@
exec "$CLI" "$@"
'''

BUILD_WHEELS_TMPL = r'''#!/usr/bin/env bash
# Rebuild @NAME@/wheels/ — the offline wheelhouse the bin/ launcher installs.
# GENERATED by scripts/gen_launchers.py — do not edit by hand; edit the template
# there and re-run it. Wheels are gitignored; Phase 3 (PyPI) removes vendoring.
# Requires uv and pip.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
WHEELS="$HERE/wheels"
STAGE="$HERE/.debug/wheels.stage"   # assembled here; swapped into wheels/ only on success
BUILD="$HERE/.debug/build"
rm -rf "$STAGE" "$BUILD"; mkdir -p "$STAGE" "$BUILD"
# A failed build (network/resolution) must never leave a half-populated wheels/
# that the launcher would treat as complete and refuse to rebuild.
trap 'rm -rf "$STAGE"' EXIT

# Pin the third-party closure to the CI-tested lockfile when present, so a fresh
# install resolves the same versions CI did rather than "latest".
CONSTRAINTS=()
[[ -f "$ROOT/constraints.txt" ]] && CONSTRAINTS=(-c "$ROOT/constraints.txt")

@BUILD_STEPS@
@CP_STEP@
@THIRD_PARTY_BLOCK@
# Record the interpreter the (ABI-specific) binary wheels target so the bin/
# launcher pins its venv to a matching Python.
python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])' > "$STAGE/.python-version"

# Swap the fully-built stage into place; set -e aborts before here on any failure.
rm -rf "$WHEELS"; mv "$STAGE" "$WHEELS"
trap - EXIT

echo "@NAME@: wheelhouse ready ($(find "$WHEELS" -name '*.whl' | wc -l | tr -d ' ') wheels, py$(cat "$WHEELS/.python-version")) in $WHEELS"
'''


def _wheel_base(dir_name: str) -> str:
    return dir_name.replace("-", "_")


def render_launcher(name: str, spec: dict) -> str:
    return (LAUNCHER_TMPL
            .replace("@ENV_TAIL@", ENV_TAILS[spec["env_tail"]])
            .replace("@NAME@", name))


def render_build_wheels(name: str, spec: dict) -> str:
    builds = spec["builds"]
    lines = []
    for i, d in enumerate(builds):
        src = '"$HERE"' if i == 0 else f'"$ROOT/{d}"'
        comment = "this plugin" if i == 0 else d
        lines.append(f'uv build --wheel --out-dir "$BUILD" {src}   # {comment}')
    build_steps = "\n".join(lines)
    globs = " ".join(f'"$BUILD"/{_wheel_base(d)}-*.whl' for d in builds)
    cp_step = f'cp {globs} "$STAGE"/'
    third = spec["third_party"]
    if third:
        third_block = (
            "\n# Vendor the third-party runtime closure (resolves the full closure for this platform).\n"
            'python3 -m pip download "${CONSTRAINTS[@]}" --only-binary=:all: --dest "$STAGE" \\\n'
            f'  {" ".join(third)}\n'
            "# Pure-python fallback for the one universal binary dep (ABI portability; best-effort).\n"
            "python3 -m pip download --no-deps --only-binary=:all: \\\n"
            "  --implementation py --abi none --platform any --python-version 3 \\\n"
            '  --dest "$STAGE" charset-normalizer || true\n'
        )
    else:
        third_block = "\n# stdlib-only: no third-party closure to vendor.\n"
    return (BUILD_WHEELS_TMPL
            .replace("@BUILD_STEPS@", build_steps)
            .replace("@CP_STEP@", cp_step)
            .replace("@THIRD_PARTY_BLOCK@", third_block)
            .replace("@NAME@", name))


def targets() -> list[tuple[Path, str, bool]]:
    """(path, content, executable) for every generated file."""
    out: list[tuple[Path, str, bool]] = []
    for name, spec in PLUGINS.items():
        out.append((ROOT / name / "bin" / name, render_launcher(name, spec), True))
        out.append((ROOT / name / "build-wheels.sh", render_build_wheels(name, spec), True))
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if any generated file is out of date")
    args = ap.parse_args()

    stale: list[Path] = []
    for path, content, executable in targets():
        current = path.read_text() if path.exists() else None
        if current == content:
            continue
        if args.check:
            stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        if executable:
            path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        print(f"wrote {path.relative_to(ROOT)}")

    if args.check and stale:
        print("Out-of-date generated files (run scripts/gen_launchers.py):", file=sys.stderr)
        for p in stale:
            print(f"  {p.relative_to(ROOT)}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
