#!/usr/bin/env bash
# Rebuild feinblick/wheels/ — the offline wheelhouse the bin/ launcher installs.
# GENERATED by scripts/gen_launchers.py — do not edit by hand; edit the template
# there and re-run it. Wheels are gitignored; Phase 3 (PyPI) removes vendoring.
# Requires uv and pip.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
WHEELS="$HERE/wheels"
STAGE="$HERE/.debug/wheels.stage"   # assembled here; swapped into wheels/ only on success
BUILD="$HERE/.debug/build"
rm -rf "$STAGE" "$BUILD"; mkdir -p "$STAGE" "$BUILD"
# A failed build (network/resolution) must never leave a half-populated wheels/
# that the launcher would treat as complete and refuse to rebuild.
trap 'rm -rf "$STAGE"' EXIT

# Pin the third-party closure to the CI-tested lockfile when present, so a fresh
# install resolves the same versions CI did rather than "latest".
CONSTRAINTS=()
[[ -f "$ROOT/constraints.txt" ]] && CONSTRAINTS=(-c "$ROOT/constraints.txt")

uv build --wheel --out-dir "$BUILD" "$HERE"   # this plugin
cp "$BUILD"/feinblick-*.whl "$STAGE"/

# stdlib-only: no third-party closure to vendor.

# Record the interpreter the (ABI-specific) binary wheels target so the bin/
# launcher pins its venv to a matching Python.
python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])' > "$STAGE/.python-version"

# Swap the fully-built stage into place; set -e aborts before here on any failure.
rm -rf "$WHEELS"; mv "$STAGE" "$WHEELS"
trap - EXIT

echo "feinblick: wheelhouse ready ($(find "$WHEELS" -name '*.whl' | wc -l | tr -d ' ') wheels, py$(cat "$WHEELS/.python-version")) in $WHEELS"
